### ISSUE TITLE
Cases Grid | top rule hit listed as general when only one hit of different category

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1164]
Top rule hit category isn't working.

1. Save rule under Federal Law Enforcement that you expect to hit
2. Rerun the messages
3. See your hits get mislabeled as General in the cases view
4. Notice your individual case for this hit has the right label

**Comment by tjwdev** [comment]
This is due to the category check is using the rule id when it needs to either use the udr_rule id or go one layer deeper to retrieve the effective udr_rule. There is not a guaranteed 1:1 relationship between the general rule id and a given udr_rule id so it defaults to general if it cannot find it (or would use whatever happenstance udr_rule category it might accidentally match on by chance). 

Will fix by retrieving UDR specific id prior to service call, as service is explicitly for retrieving udr_rules and do not wish to muddy its purpose.
