### ISSUE TITLE
UI - Admin>Loader Stats connectivity -> REACT

### ISSUE THREAD

**Issue by gtasautumn** [US-CBP/GTAS#1583]
Add required endpoints to ServiceWrapper, pull the data into the page

**Comment by TeddyTesfaye** [comment]
Current state  of the checked in code for this feature: 
1. The loader statistics data is displayed on the Loader Statistics tab
2. The Refresh button successfully refreshes data on the page.
3. Input fields are read-only

Outstanding issue:
For those fields for which the back-end service returns 0 as a valid value, the UI shows a blank input field, instead of displaying the returned 0.

**Comment by originalname51** [comment]
values coming back
