### ISSUE TITLE
Parser | nonstandard UNA segments for PNR messages incorrectly parsing underscores for email addresses

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1742]

**Comment by tjwdev** [comment]
Below is a edited segment of a PNR message with a non-standard UNA segment:

UNA!@#$ ^
...
IFT@4!28!!YY@CTCE SHARONDA##OSORIO//GMAIL#COM^
...

The issue as is appears that in our free text element there are advice strings in the midst of it that are not being converted to their equivalents due to the nature of it being a free text element.

The current conclusion being that these advice strings would not be present in a free text field. There is a separate issue with FOP using the same advice strings to delimit payment decimals, but another ticket will be made and opened linking to this one about it.
