### ISSUE TITLE
Passenger History | Current PNR Itinerary

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#206]
Flight not on current PNR is showing up in the Travel History section, under current itinerary. Searching for airport code "TLL" in the PNR section, returns no results (focusing on the TVL areas of the PNR). 

This flight should be in the Total History section.

![uploads/0a505431-8b10-4abc-ad43-9f52d12b5a86/Monosnap 2017-01-19 09-29-28.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0a505431-8b10-4abc-ad43-9f52d12b5a86%2FMonosnap+2017-01-19+09-29-28.png)

![uploads/d5be7cba-822d-4226-b837-2332b341ae80/Monosnap 2017-01-19 09-30-11.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd5be7cba-822d-4226-b837-2332b341ae80%2FMonosnap+2017-01-19+09-30-11.png)

**Comment by jtangGitHub** [comment]
I retested the ticket with test data (KEVIN FLATLEY) and found out:
1. First, the front end code made the call to back end API (getFlightHistoryByPassengerAndDocuments())to get the flight history for the interested passenger. In this case, there were two cases from all itineraries in the current and in the past.
2. Then, the front end made the call to back end API (getTravelHistoryByPassengerAndDocument())to get travel history for the interested passenger. It returned none because the current flight itinerary is excluded in the search result.

Jonathan, please review flight/travel display code in the front end.

**Comment by dje04001** [comment]
unable to recreate. appears to be fixed.
