### ISSUE TITLE
Expected segment TVL but got wrong segment

### ISSUE THREAD

**Issue by lbigo693** [US-CBP/GTAS#2118]
PNR version 15.1 not send second TVL segment in group 5 for the specification of code-
share flight information

**Comment by originalname51** [comment]
This appears to be related to how GTAS processes code share flights. 

GTAS currently will look for two TVL lines, which is not recommended for spec > 14.1. 

There will need to be an update to look in the TRA field instead of for a second TVL.

GTAS also is forcing a mandatory check on the second TVL which will cause messages that have TRA describe the code share flight fail.

The update would be to have GTAS look for a TRA segment and use that for the code share if available while keeping the pre 14.1 for backwards compatibility as well.

Effected segments likely start on line 463 of the PnrGovParser.java.

**Comment by originalname51** [comment]
This has been addressed in https://github.com/US-CBP/GTAS/releases/tag/v1.14.2 .

Thank you for reporting it!
