### ISSUE TITLE
Parser | Investigate Parsing Issues for UNEDIFACT

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#232]
Files "Test 1" and "Test 3" are in the google drive under test docs, in the folder "Data Generated in UNEDIFACT 12B format, with 02B header info". I was having a hard time getting 12B data to load, so I changed the headers to match a successful 02B file and the import was successful. I'll add more 02B format files shortly.

**Comment by dje04001** [comment]
Srini, the two files in the 02B format were made in the 02B format entirely. It's probably best to start analysis with these files.

**Comment by svempati2006** [comment]
Sure.I will


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*

**Comment by svempati2006** [comment]
Two issues were found.
1).The raw message is failing get updated to Database due to the default collation latin_swedish_ci.Changing the default collation to utf8_general_ci while creating the GTAS schema in DB resolved the issue.
2).The files LOC segment for resdiency country was entered wrong country code "GER".Changing it to right country code resolved the loading issue.
