### ISSUE TITLE
New Feature | Whitelist [#72]

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#38]
For diplomats, VIPs - might be embarrassing to send them to secondary

**Comment by svempati2006** [comment]
Requirement is unclear.Please elaborate.

**Comment by dje04001** [comment]
LN, FN, DOB, one of the document IDs are required to match whitellist

**Comment by dje04001** [comment]
still show up on pax search, suppress hits so they don't show

**Comment by dje04001** [comment]
Set expectation for how long that will take upon completion of ticket No. 20.

**Comment by jtangGitHub** [comment]
identified the attributes below as input fields for whitelist view

firstname, middlename, lastname, gender, dob, citizenshipCountry, residencycountry, 
AND 
documentType, documentNumber, expirationDate, issuranceDate, issuranceCountry

need to know which attributes are **required** in order to flag a passenger as an VIP?

currently, an VIP is identified for those fields that needed to match to messages.  (no nulls)

**Comment by dje04001** [comment]
First Name, Last Name, DOB, Document Number, Document Expiration Date are all required
