### ISSUE TITLE
Prod Data | Phone Number in LTS segment 

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#398]
LTS+0/5/API

**Comment by svempati2006** [comment]
The PNRGOV specification doesn't have any phone number pattern to identify and parse the..Please see below segment info..If we get any meaningful phone number format from PROD data we can work against.Otherwise this ticket can be closed..
===============================
Unstructured PNR history from LTS.
LTS+ LAX GS WW D006217 2129Z/09DEC 02961B AS DL1314U 19FEB MCOATL NN/SS1
1130A 105P AS SEAT RS 29F TRAN/TRINH DL1314 19FEB MCOATL AS DL1319T
23FEB ATLMCO NN/SS1 355P 524P¬AS SEAT RS 28A TRAN/TRINH DL1319 23FEB
ATLMCO A$ 4P A-USD 160.93 TX 33.27 TTL 194.20 WW09DEC AC A ORL DL
ATL87.44UA10A0SJ DL ORL73.49TA10X3SJ USD160.93END ZP MCOATL XF MCO4.5ATL4.5 PS
LAXADLLAX LAXGSWWUS LAXDL -LAX GS WW D006217 09DEC2129Z 02961B XS DL1314U
19FEB MCOATL NN/HK1 1130A 105P XS SEAT XR/RS 29F TRAN/TRINH DL1314 19FEB
MCOATL XS DL1319T 23FEB ATLMCO NN/HK1 355P 524P XS SEAT XR/RS 28A TRAN/TRINH
DL1319 23FEB ATLMCO X$ 4P A-USD 160.93 TX 33.27 TTL 194.20 WW09DEC XC A ORL
DL ATL87.44UA10A0SJ DL ORL73.49TA10X3SJ USD160.93END ZP MCOATL XF MCO4.5ATL4.5 XE
A-USD XF-9.00/ZP-7.20/AY-5.00/US-12.07/ XT TKT-TE/1200N/09DEC -LAX GS WW D006217
09DEC2129Z 02961B’
===================================

**Comment by dje04001** [comment]
more descriptive tickets have been created to address these data elements.
