### ISSUE TITLE
Passenger Details | failing to pass data to front end

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#461]

**Comment by tjwdev** [comment]
NPE due to attempting to read data_source property of bag.  Line 226, PassengerDetailsController.java. PNR message loader has function createBagsFromPnrVo(...) that assigns a data_source to the bag, however, APIS message loader does not have a corresponding function. If we only receive an APIS file it does not set a data_source (amongst other things) and forces a NPE later.

**Comment by svempati2006** [comment]
Code completed unit tested and checked into GitHub.Pl review.
