### ISSUE TITLE
Data | Seat assignment from SSD segment

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#464]
We are not displaying the seat assignment form the SSD segment on the Passenger Detail tab if we have it. It displays properly on the PNR tab.

**Comment by donleyac** [comment]
After investigating, when info appears on pnr and not on passenger details it is because seat data exists for another passenger on the same pnr but not the specific passenger you are viewing. I looked into a specific passenger where this was the case, they simply didn't have a seat assignment in the database. I then looked at the pnr raw which had this line  SSD+15A++++Y', which I assume mean indicates seat 15A. I checked the database and 15A does not exist. This is some weird parsing/loading issue where some passengers on a pnr have a seat assignment while others do not.

**Comment by originalname51** [comment]
Issue appears to be working with recent iteration of GTAS. Please re-open if issue still here.
