### ISSUE TITLE
PNR Tab | Bag ID not displaying properly

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#536]
Each Traveler can have their own set of bag IDs. Right now only one bag ID is showing.

**Comment by donleyac** [comment]
Apis Tab: 
1. Apis Message is obtained by Flight Id & Pax ID
2. Passenger t is passenger is obtained by Pax ID
3. Passengers have 1-to-many relationship with Bags. t.getBags() is used to get set of Bags associated with passenger. These are added to apisvo when sent to Frontend. 

Pnr Tab:
1. Pnr message is obtained by Flight Id and Pax ID
2.  Passenger t is passenger is obtained by Pax ID
3. Passengers have 1-to-many relationship with Bags. t.getBags() is used to get set of Bags associated with passenger. These are added to pnrvo when sent to Frontend. 

Bottom Line: Apis Message, PNR & Flight Pax are not used to obtain Bag ID. Only Pax ID.
The problem is that bags only has getters/setters tied to passengers, we could define another service to obtain bag Id only by passenger & Flights. This will prevent bags from surfacing across different flights. However, this won't solve showing all the bags for each traveller on a pnr and apis message. What we need to do is maintain a many-to-one relationship between flightpax table and pnr & apis. If we want to get the set of passenger/flight info we simply just need to filter on the pnr and apis table.

**Comment by donleyac** [comment]
Basically we should move the association from Bags to passenger and tie it directly to the flight-pax table.

**Comment by donleyac** [comment]
@svempati2006

**Comment by dje04001** [comment]
We're completely redesigning the bag model
