### ISSUE TITLE
Big Data Warehouse

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#54]

**Comment by dje04001** [comment]
The passenger history really needs further development before this feature can be added. Moving ticket out of sprint.

**Comment by svempati2006** [comment]
Actually these kind of analytics are possible against historical data.I
have some design documents to show.Since we receive million records a day
the simple java solution we developed will not sustain the load and can not
provide data for efficient search.
We can redesign the same solution using Big data.
Basically we receive the messages to Kafka messaging system.From Kafka our
parser code will act as readers and store the data in immutable storage as
well as intermediate tables called Hive.From there we can run analytics and
develop some patterns to find anomalies.Also we can use the web front to
show the data like we are showing now.
The goal is Zillion records -million column data available in milli seconds
for search.If you want to take a look  i can prepare the solution design to
go over some time next week.


Thank you,
Srinivasarao Vempati.

*Capital Infotech Inc.*

*41969 Ural Dr.*

*STONE RIDGE.*

*VA-20105.*
*Ph:703-340-0906.*
