### ISSUE TITLE
Fix formatting issues on flight/pax filters

### ISSUE THREAD

**Issue by copenhafer** [US-CBP/GTAS#6]
Some general formatting issues with the current filters on both flight and pax views: (1) origin and dest are too large; (2) direction element doesn't line up; (3) reset and filter buttons are cramped (spread things out more if possible).

**Comment by tjwdev** [comment]
Flight/Pax filter input fields fixed in terms of alignment locally for chrome/ff. Origin and Destination have had their sizes reduced by 25% as well as having clear delineation between them and other input fields. The direction element should appropriately be vertically aligned now. Unfortunately, very little real estate to work with on the Pax screen for spreading elements further.
