### ISSUE TITLE
PNR Tab | Documents Table shows documents from APIS

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#624]
This section should only show documents that are contained in the PNR message

**Comment by donleyac** [comment]
It is because documents are tied to passenger. We could tie document to the flightpax table and add a data source property to it. However, this will also make it more difficult to view a specific person's documents. We would have to look through the most recent flight paxes and get the documents used. It is definitely do-able will also help use maintain a history of documents that person has used.  
@svempati2006
