### ISSUE TITLE
APIS loading error | Progressive Flights

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#813]
ERROR gov.gtas.services.ApisMessageService - javax.validation.ConstraintViolationException: Validation failed for classes [gov.gtas.model.BookingDetail] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='size must be between 4 and 4', propertyPath=flightNumber, rootBeanClass=class gov.gtas.model.BookingDetail, messageTemplate='{javax.validation.constraints.Size.message}'}

**Comment by dje04001** [comment]
There is a sample file in the shared drive under github tickets / 813. This is a flavor of message we haven't tested for before--progressive flights. This type of message is for a border crossing flight, that continues on to another destination within the same country.

**Comment by dje04001** [comment]
please work together on this one. I think this is a good chance for Geoffrey to learn about the data and the parser/loader.

**Comment by geoffbays** [comment]
Analysis: With an assist from Jonathan, here is the problem: the Apis file has an issue with the progressive flight line: 
The primary flight (line 8) parses fine: TDT+20+XZ877+++XZ', but the progressive flight(line 13) does not parse as intended: TDT+20+ZX877+++XZ' because the carrier code is 'ZX' is the first part of the TDT line, but 'XZ' in the last part of the TDT line. We suspect that the second TDT line should have been the same as the first, with 'XZ' in both places, same carrier and same flight number as the primary flight. If the carrier had changed to 'ZX' that value in both places in line 13 would have parsed correctly as well.
The larger question of how Apis should handle secondary, BookingDetail flights may need some clarification.
